# Generated by Django 3.2.7 on 2021-10-06 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0003_executors_telegrams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executors',
            name='unit',
            field=models.CharField(choices=[('A2326', 'A2326'), ('A1314', 'A1314'), ('MARCH', 'March'), ('DECEMBER', 'December')], max_length=100),
        ),
    ]
