# Generated by Django 3.2.8 on 2021-10-07 11:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0004_alter_executors_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrams',
            name='confirm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='telegrams',
            name='deadline',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='telegrams',
            name='note',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='telegrams',
            name='priority',
            field=models.CharField(choices=[('Висока', '1'), ('Низька', '0')], default='Висока', max_length=20),
        ),
        migrations.AddField(
            model_name='telegrams',
            name='tlg_number',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='telegrams',
            name='tlg_scan',
            field=models.FileField(null=True, upload_to='tlg_dir/'),
        ),
        migrations.AlterField(
            model_name='executors',
            name='unit',
            field=models.CharField(max_length=100),
        ),
    ]
