# Generated by Django 3.2.7 on 2021-10-07 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0005_auto_20211007_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegrams',
            name='priority',
            field=models.CharField(blank=True, choices=[('1', 'Висока'), ('0', 'Низька')], max_length=20),
        ),
        migrations.AlterField(
            model_name='telegrams',
            name='tlg_scan',
            field=models.FileField(blank=True, null=True, upload_to='tlg_dir/'),
        ),
    ]
