# Generated by Django 3.2.8 on 2022-02-09 13:36

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import panel.models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0006_auto_20211007_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegrams',
            name='confirm',
            field=models.BooleanField(default=False, verbose_name='Телеграма виконана!'),
        ),
        migrations.AlterField(
            model_name='telegrams',
            name='deadline',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Виконати до'),
        ),
        migrations.AlterField(
            model_name='telegrams',
            name='description',
            field=models.TextField(verbose_name='Опис телеграми'),
        ),
        migrations.AlterField(
            model_name='telegrams',
            name='note',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Примітки'),
        ),
        migrations.AlterField(
            model_name='telegrams',
            name='priority',
            field=models.CharField(choices=[('1', 'Висока'), ('0', 'Низька')], default='0', max_length=20, verbose_name='Важливість телеграми'),
        ),
        migrations.AlterField(
            model_name='telegrams',
            name='tlg_number',
            field=models.CharField(max_length=100, null=True, verbose_name='Номер вихідної телеграми'),
        ),
        migrations.AlterField(
            model_name='telegrams',
            name='tlg_scan',
            field=models.FileField(blank=True, null=True, upload_to=panel.models.user_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Завантажити скан-копію телеграми'),
        ),
    ]
