# Generated by Django 3.2.11 on 2022-02-02 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarcontrol', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramscontrol',
            name='confirm',
            field=models.BooleanField(default=False, verbose_name='Телеграма виконана!'),
        ),
        migrations.AlterField(
            model_name='telegramscontrol',
            name='date',
            field=models.CharField(blank=True, max_length=200, verbose_name='Дата виконання:'),
        ),
        migrations.AlterField(
            model_name='telegramscontrol',
            name='priority',
            field=models.CharField(choices=[('1', 'Висока'), ('0', 'Низька')], default=0, max_length=20, verbose_name='Важливість телеграми'),
        ),
    ]
